# Generated by Django 5.2.1 on 2025-06-06 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('numero', models.AutoField(help_text='Numero da venda', primary_key=True, serialize=False)),
                ('data_venda', models.DateField(blank=True, default=datetime.datetime(2025, 6, 6, 23, 33, 35, 651818, tzinfo=datetime.timezone.utc), help_text='data da venda', null=True)),
                ('valor_venda', models.FloatField(help_text='Valor da venda')),
                ('cliente_cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
