# Generated by Django 5.2.1 on 2025-06-18 01:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '__first__'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('numero', models.AutoField(help_text='Numero da venda', primary_key=True, serialize=False)),
                ('dataVenda', models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 18, 1, 40, 41, 529560, tzinfo=datetime.timezone.utc), help_text='data da venda', null=True)),
                ('valorVenda', models.FloatField(help_text='Valor da venda')),
                ('clienteCpf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienteCpf', to='clientes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='item_venda',
            fields=[
                ('numero', models.AutoField(help_text='Numero da venda', primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(help_text='quantidade do item')),
                ('precoVenda', models.FloatField(help_text='Preço de venda do produto')),
                ('produtoCodigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtoCodigo', to='produtos.produtos')),
                ('vendaNumero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendaNumero', to='venda.venda')),
            ],
        ),
    ]
