# Generated by Django 5.2.1 on 2025-06-19 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='dataVenda',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 19, 15, 41, 55, 107879, tzinfo=datetime.timezone.utc), help_text='data da venda', null=True),
        ),
    ]
