# Generated by Django 5.2.1 on 2025-06-08 14:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cliente_cpf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to='clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 8, 14, 16, 31, 658625, tzinfo=datetime.timezone.utc), help_text='data da venda', null=True),
        ),
    ]
