# Generated by Django 5.2.1 on 2025-06-08 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_alter_venda_cliente_cpf_alter_venda_data_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 8, 14, 35, 15, 210706, tzinfo=datetime.timezone.utc), help_text='data da venda', null=True),
        ),
    ]
