# Generated by Django 5.2.1 on 2025-06-16 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_alter_venda_data_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 16, 0, 38, 5, 18703, tzinfo=datetime.timezone.utc), help_text='data da venda', null=True),
        ),
    ]
