# Generated by Django 5.2.1 on 2025-06-17 20:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_rename_fabricante_codigo_produtos_fornecedores_codigo_and_more'),
        ('venda', '0005_alter_venda_data_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 17, 20, 28, 3, 779389, tzinfo=datetime.timezone.utc), help_text='data da venda', null=True),
        ),
        migrations.CreateModel(
            name='item_venda',
            fields=[
                ('numero', models.AutoField(help_text='Numero da venda', primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(help_text='quantidade do item')),
                ('preco_venda', models.FloatField(help_text='Preço de venda do produto')),
                ('produto_codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_produto', to='produtos.produtos')),
                ('venda_numero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_venda', to='venda.venda')),
            ],
        ),
    ]
