# Generated by Django 5.2.1 on 2025-06-18 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0006_alter_venda_data_venda_item_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 18, 1, 14, 26, 16457, tzinfo=datetime.timezone.utc), help_text='data da venda', null=True),
        ),
    ]
