# Generated by Django 5.2.1 on 2025-06-18 01:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_emaildocliente_clientes_email_and_more'),
        ('produtos', '0005_rename_preco_compra_produtos_precocompra_and_more'),
        ('venda', '0007_alter_venda_data_venda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_venda',
            old_name='preco_venda',
            new_name='precoVenda',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='valor_venda',
            new_name='valorVenda',
        ),
        migrations.RemoveField(
            model_name='item_venda',
            name='produto_codigo',
        ),
        migrations.RemoveField(
            model_name='item_venda',
            name='venda_numero',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='cliente_cpf',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='data_venda',
        ),
        migrations.AddField(
            model_name='item_venda',
            name='produtoCodigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtoCodigo', to='produtos.produtos'),
        ),
        migrations.AddField(
            model_name='item_venda',
            name='vendaNumero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendaNumero', to='venda.venda'),
        ),
        migrations.AddField(
            model_name='venda',
            name='clienteCpf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienteCpf', to='clientes.clientes'),
        ),
        migrations.AddField(
            model_name='venda',
            name='dataVenda',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 18, 1, 16, 53, 673777, tzinfo=datetime.timezone.utc), help_text='data da venda', null=True),
        ),
    ]
