# Generated by Django 5.2.1 on 2025-06-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('codigo', models.AutoField(help_text='Codigo do produto', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do produto', max_length=70)),
                ('precoDeCompra', models.FloatField(help_text='Preço de compra do Produto')),
                ('precoDeVenda', models.CharField(help_text='Preço de venda do produto')),
                ('cor', models.CharField(help_text='Cor do produto', max_length=20)),
                ('dataFabricacao', models.DateField(help_text='Cidade do cliente', max_length=50)),
                ('imagem', models.CharField(help_text='Nome da imagem do produto', max_length=25)),
            ],
        ),
    ]
