# Generated by Django 5.2.1 on 2025-06-18 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('codigo', models.AutoField(help_text='Codigo do produto', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do produto', max_length=70)),
                ('precoCompra', models.FloatField(help_text='Preço de compra do Produto')),
                ('precoVenda', models.FloatField(help_text='Preço de venda do produto')),
                ('cor', models.CharField(help_text='Cor do produto', max_length=20)),
                ('imagem', models.CharField(help_text='Nome da imagem do produto', max_length=25)),
                ('fornecedoresCodigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedoresCodigo', to='fornecedores.fornecedores')),
            ],
        ),
    ]
