# Generated by Django 5.2.1 on 2025-06-16 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produtos_fabricante_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='precoDeCompra',
            new_name='preco_Compra',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='precoDeVenda',
            new_name='preco_Venda',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='dataFabricacao',
        ),
    ]
