# Generated by Django 5.2.1 on 2025-06-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_rename_precodecompra_produtos_preco_compra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='fabricante_codigo',
            new_name='fornecedores_codigo',
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco_Venda',
            field=models.FloatField(help_text='Preço de venda do produto'),
        ),
    ]
