# Generated by Django 5.2.1 on 2025-06-18 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('produtos', '0004_rename_fabricante_codigo_produtos_fornecedores_codigo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='preco_Compra',
            new_name='precoCompra',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='preco_Venda',
            new_name='precoVenda',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='fornecedores_codigo',
        ),
        migrations.AddField(
            model_name='produtos',
            name='fornecedoresCodigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedoresCodigo', to='fornecedores.fornecedores'),
        ),
    ]
