# Generated by Django 5.2.1 on 2025-06-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cpf', models.CharField(help_text='Cpf do cliente', max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do cliente', max_length=70)),
                ('endereco', models.CharField(help_text='Endereço do Cliente', max_length=100)),
                ('telefone', models.CharField(help_text='Telefone do cliente', max_length=11)),
                ('uf', models.CharField(help_text='Estado de Domicilío do cliente', max_length=2)),
                ('cidade', models.CharField(help_text='Cidade do cliente', max_length=50)),
                ('genero', models.CharField(help_text='Genero do cliente', max_length=1)),
                ('contato', models.CharField(help_text='Contato do cliente', max_length=1)),
                ('email', models.CharField(help_text='E-mail do cliente', max_length=100)),
                ('senha', models.CharField(help_text='Senha', max_length=256)),
            ],
        ),
    ]
