# Generated by Django 5.2.1 on 2025-06-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(help_text='CPF do cliente', max_length=14, primary_key=True, serialize=False, unique=True),
        ),
    ]
