# Generated by Django 5.2.1 on 2025-06-16 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='emailDoCliente',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='estadoDeDomicilio',
            new_name='uf',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='nomeDoUsuario',
        ),
    ]
